# Generated by Django 4.0.4 on 2022-04-30 11:20

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specie_name', models.CharField(blank=True, help_text='Use Scientific Name', max_length=200, null=True, verbose_name='Specie Name')),
                ('kinyarwanda_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kinyarwanda Name')),
                ('sampling_method', models.CharField(max_length=200, verbose_name='Sampling Method')),
                ('sampling_date', models.DateTimeField(auto_now_add=True, verbose_name='Sampling Date')),
                ('site_description', models.TextField(blank=True, help_text='Describe site including location name', null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('project_name', models.CharField(blank=True, help_text='Tell us in short the project that you are currently working on if any.', max_length=100, null=True, verbose_name='Project Name')),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='pending', max_length=100)),
                ('thumbnail', models.ImageField(null=True, upload_to=core.models.uploadToMedia)),
            ],
        ),
    ]
